export const ADD_MOVIE_TO_CART = 'ADD_MOVIE_TO_CART';

export const REMOVE_MOVIE_FROM_CART = 'REMOVE_MOVIE_FROM_CART';

export const GET_NR_OF_PRODUCTS_FROM_CART = 'GET_NR_OF_PRODUCTS_FROM_CART';

export const UPDATE_CART_UNITS = 'UPDATE_CART_UNITS';

export const CLEAR_CART = 'CLEAR_CART';

export const GET_TOTAL_COST_OF_CART = 'GET_TOTAL_COST_OF_CART';

export const DECREASE_MOVIES_FROM_CART = 'DECREASE_MOVIES_FROM_CART';
export const INCREASE_MOVIES_FROM_CART = 'INCREASE_MOVIES_FROM_CART';
